on: [push]
name: "Docker build"
jobs:
#    build-whole-application:
#        name: Build application and run standards checks and tests
#        runs-on: 'ubuntu-20.04'
#        steps:
#            -   name: GIT checkout branch - ${{ github.ref }}
#                uses: actions/checkout@v2
#                with:
#                    ref: ${{ github.ref }}
#            -   name: Build application
#                run: echo 1 | ./scripts/install.sh
#            -   name: Check standards
#                run: docker-compose exec -T php-fpm php phing standards
#            -   name: Run tests
#                run: docker-compose exec -T php-fpm php phing tests
#            -   name: Run acceptance tests
#                run: docker-compose exec -T php-fpm php phing tests-acceptance
#            -   name: PHP-FPM container logs
#                if: ${{ failure() }}
#                run: docker-compose logs php-fpm
#            -   name: Copy Codeception logs from container
#                if: ${{ failure() }}
#                run: docker cp shopsys-framework-php-fpm:/var/www/html/var/log ./var/log
#            -   name: Upload Codeception logs to artifacts
#                if: ${{ failure() }}
#                uses: actions/upload-artifact@v2
#                with:
#                    name: acceptance-logs
#                    path: ./var/log
    mac-os-test:
        name: Docker on MacOS test
        runs-on: macos-latest
        steps:
            -   name: GIT checkout branch - ${{ github.ref }}
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.ref }}
            -   name: Setup Docker
                uses: docker-practice/actions-setup-docker@master
                with:
                    docker_channel: stable
            -   name: Build application prerequirements on MacOS
                run: cp -f ./.github/docker-compose.mac.yml.dist ./docker-compose.yml
            -   run: docker-compose up -d
            -   run: docker cp ./ shopsys-framework-php-fpm:/var/www/html
            -   run: docker cp ./docker/postgres/postgres.conf shopsys-framework-postgres:/var/lib/postgresql/data/postgresql.conf
            -   run: docker cp ./docker/nginx/nginx.conf shopsys-framework-webserver:/etc/nginx/conf.d/default.conf
            -   run: docker-compose exec -T php-fpm composer install
            -   run: docker-compose exec -T php-fpm php phing build-demo-dev-quick
            -   run: docker cp shopsys-framework-php-fpm:/var/www/html/web ./web
            -   run: docker cp ./web shopsys-framework-webserver:/var/www/html/web
            -   run: docker-compose exec -T php-fpm php phing standards
            -   run: docker-compose exec -T php-fpm php phing tests
            -   run: docker-compose exec -T php-fpm php phing tests-acceptance
